vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        plats:
            uri_prefix: /PlatsImages/images
            upload_destination: '%kernel.project_dir%/public/PlatsImages/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer