controllers:
    resource: ../src/Controller/
    type: attribute
auth:
    path: /auth
    methods: ['POST']
livreur_location_update:
    path: '/livreur/location/update'
    controller: App\Controller\LivreurController::updateLocation
    methods: [GET, POST]

